[build]
  functions = "netlify/functions"
  command = "npm run build"
  publish = "dist"
  base = "/"

[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200

[[plugins]]
  package = "@netlify/plugin-emails"
