[build]
  command = "npm run build"
  publish = "dist/index.js"
  functions = "netlify/functions"

[[plugins]]
  package = "@netlify/plugin-emails"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
